title: Elizabeth Saraf # your name (or website title) here
logo: "/images/Saraf.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Undergraduate Student at the University of Rhode Island
  Narragansett, RI 02882
  <br><br>
  <a href="https://twitter.com/elizabethsaraf1></a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
